export const REQUEST_PROFILE_START = "REQUEST_PROFILE_START";
export const REQUEST_PROFILE_FINISHED = "REQUEST_PROFILE_FINISHED";
export const REQUEST_PROFILE_FAILED = "REQUEST_PROFILE_FAILED";
export const REQUEST_FEATURED_POSTS_START = "REQUEST_FEATURED_POSTS_START";
export const REQUEST_FEATURED_POSTS_FINISHED = "REQUEST_FEATURED_POSTS_FINISHED";
export const REQUEST_FEATURED_POSTS_FAILED = "REQUEST_FEATURED_POSTS_FAILED";